# 再起動時刻（秒まで指定可能）
restart-times:
  - "04:00:00"
  - "20:15:30"

# 何秒前に通知するか
notify-before:
  - 300
  - 60

# 指定時刻にコマンドを実行する
scheduled-commands:
  task1:
    time: "03:40:10"
    command: "say 自動タスク実行"
  task2:
    time: "05:00:00"
    command: "say haro-"
