#すべて24時間制
# 再起動時刻（複数設定可能）
restart-times:
  - "04:00"

# 何分前に通知するか
notify-before:
  - 5
  - 1

# 時刻指定コマンド実行
scheduled-commands:
  command1:
    time: "03:30"
    command: ""
  command2:
    time: "05:00"
    command: ""
